name: Café Asil Session Generator

on:
  workflow_dispatch:
    inputs:
      playlist-name:
        description: 'Choose playlist type'
        required: true
        type: choice
        options:
          - lofi-moments
          - sleepy-cafe
          - study&focus-mixes
          - morning-brew
      existing-session:
        description: 'Enter existing session name {YYYYMMDD} (leave empty to create new)'
        required: false
        default: ''

jobs:
  prepare-and-merge:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asil-records/create-session-image:v1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Write rclone config
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
          echo "Config file written."

      - name: Prepare workflow variables
        id: vars
        run: |
          PLAYLIST_NAME="${{ github.event.inputs.playlist-name }}"
          EXISTING_SESSION="${{ github.event.inputs.existing-session }}"
          SESSION_DATE=$(date +%Y%m%d)

          if [ -n "$EXISTING_SESSION" ]; then
            SESSION_NAME=session-${EXISTING_SESSION}
            TARGET_PATH="cafe-asil:Asil-Records/music/${PLAYLIST_NAME}/${SESSION_NAME}"
          else
            SESSION_NAME=session-${SESSION_DATE}
            TARGET_PATH="cafe-asil:Asil-Records/music/${PLAYLIST_NAME}/${SESSION_NAME}"
          fi

          ASSETS_PATH="${TARGET_PATH}/assets"
          MERGED_MP3_FILE="merged-${PLAYLIST_NAME}-${SESSION_DATE}.mp3"
          MERGED_MP4_FILE="merged-${PLAYLIST_NAME}-${SESSION_DATE}.mp4"
          FINAL_MP4_FILE="final-${PLAYLIST_NAME}-${SESSION_DATE}.mp4"

          echo "SESSION_NAME=${SESSION_NAME}" >> GITHUB_ENV
          echo "TARGET_PATH=${TARGET_PATH}" >> $GITHUB_ENV
          echo "ASSETS_PATH=${ASSETS_PATH}" >> $GITHUB_ENV
          echo "MERGED_MP3_FILE=${MERGED_MP3_FILE}" >> $GITHUB_ENV
          echo "MERGED_MP4_FILE=${MERGED_MP4_FILE}" >> $GITHUB_ENV
          echo "FINAL_MP4_FILE=${FINAL_MP4_FILE}" >> $GITHUB_ENV
          echo "NEW_SESSION_CREATED=${NEW_SESSION_CREATED}" >> $GITHUB_ENV

      - name: Ensure folders exist and set flag
        run: |
          echo "Ensuring required folders exist..."
          NEW_SESSION_CREATED=false
      
          # Check if the session (TARGET_PATH) exists
          if rclone lsd "${TARGET_PATH}" >/dev/null 2>&1; then
            echo "Session folder already exists."
            echo "- ${TARGET_PATH} already exists." >> $GITHUB_STEP_SUMMARY
      
            # Session exists, check assets folder inside it
            if rclone lsd "${ASSETS_PATH}" >/dev/null 2>&1; then
              echo "Assets folder already exists, skipping creation."
              echo "- ${ASSETS_PATH} already exists." >> $GITHUB_STEP_SUMMARY
            else
              echo "Assets folder missing, creating..."
              rclone mkdir "${ASSETS_PATH}" || { echo "Failed to create ${ASSETS_PATH}"; exit 1; }
              echo "Assets folder created successfully."
              echo "- Created ${ASSETS_PATH}" >> $GITHUB_STEP_SUMMARY
              NEW_SESSION_CREATED=true
            fi
      
          else
            # Session does not exist → create both at once
            echo "Session folder not found, creating both session and assets folders..."
            rclone mkdir "${TARGET_PATH}" || { echo "Failed to create ${TARGET_PATH}"; exit 1; }
            rclone mkdir "${ASSETS_PATH}" || { echo "Failed to create ${ASSETS_PATH}"; exit 1; }
            echo "- Created ${TARGET_PATH}" >> $GITHUB_STEP_SUMMARY
            echo "- Created ${ASSETS_PATH}" >> $GITHUB_STEP_SUMMARY
            NEW_SESSION_CREATED=true
          fi
      
          # Export flag for later steps
          echo "NEW_SESSION_CREATED=${NEW_SESSION_CREATED}" >> $GITHUB_ENV
        
      - name: Download all session audio files
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          mkdir -p ./session_audio
          echo "Downloading MP3s from ${TARGET_PATH}..."
          rclone copy "${TARGET_PATH}" ./session_audio --include "*.mp3" --progress

      - name: Prepare audio files for FFmpeg merge
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "🎵 Creating FFmpeg file list..."
          find ./session_audio -type f -name "*.mp3" | sort | while read f; do
            echo "file '$f'" >> mp3_file_list.txt
          done
      
          echo "File list created for FFmpeg:"
          cat mp3_file_list.txt
      
          if [ ! -s mp3_file_list.txt ]; then
            echo "No MP3 files found — aborting merge."
            exit 1
          fi
      
          echo "- Found $(wc -l < mp3_file_list.txt) tracks for merging." >> $GITHUB_STEP_SUMMARY

      - name: Merge audio with FFmpeg
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "Merging MP3s into one file..."
          ffmpeg -f concat -safe 0 -i mp3_file_list.txt -c copy merged_output.mp3 -y || { echo "FFmpeg merge failed"; exit 1; }
          echo "Merge completed successfully!"
          echo "- Audio merge completed successfully!" >> $GITHUB_STEP_SUMMARY 
          ls -lh merged_output.mp3

      - name: Download all asset videos
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "Downloading asset videos from Drive..."
          mkdir -p ./assets
          rclone copy "${ASSETS_PATH}" ./assets --include "*.mp4" --progress
          echo "Assets downloaded successfully."
          ls -l ./assets

      - name: Merge MP4 files
        if: env.NEW_SESSION_CREATED != 'true'
        run: |

          # Create file list for ffmpeg
          find ./assets -maxdepth 1 -type f -name "*.mp4" | sort | while read f; do
            echo "file '$f'" >> mp4_file_list.txt
          done

          echo "File list for ffmpeg:"
          cat mp4_file_list.txt

          if [ ! -s mp4_file_list.txt ]; then
            echo "No mp4 files found — aborting merge."
            exit 1
          fi
      
          echo "- Found $(wc -l < mp4_file_list.txt) tracks for merging." >> $GITHUB_STEP_SUMMARY

      - name: Merge audio with FFmpeg
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "Merging MP4s into one file..."
          ffmpeg -f concat -safe 0 -i mp4_file_list.txt -c copy merged_video.mp4 -y || { echo "FFmpeg merge failed"; exit 1; }
          echo "Merge completed successfully!"
          echo "- Video merge completed successfully!" >> $GITHUB_STEP_SUMMARY
          ls -lh merged_video.mp4

      - name: Merge merged video and audio into final output
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "Merging mp4 and mp3 into final_output.mp4..."

          # Ensure both files exist
          if [ ! -f merged_video.mp4 ]; then
            echo "merged_video.mp4 not found!"
            exit 1
          fi

          if [ ! -f merged_output.mp3 ]; then
            echo "merged_output.mp3 not found!"
            exit 1
          fi

          # Merge audio and video
          ffmpeg -stream_loop -1 -i merged_video.mp4 -i merged_output.mp3 \
            -shortest -c:v libx264 -c:a aac -pix_fmt yuv420p final_output.mp4 -y

          echo "✅ Final video created successfully at final_output.mp4"
          echo "- Merged final_output.mp4 successfully." >> $GITHUB_STEP_SUMMARY

      - name: Upload final video back to Drive
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "Uploading final version to Drive..."
          rclone copy final_output.mp4 "${ASSETS_PATH}/${FINAL_MP4_FILE}" --progress
          echo "Finished video uploaded successfully." >> $GITHUB_STEP_SUMMARY

      - name: Add completion summary
        if: env.NEW_SESSION_CREATED != 'true'
        run: |
          echo "### ☕ Café Asil **${SESSION_NAME}**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Playlist: **${{ github.event.inputs.playlist-name }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Session Path: **${TARGET_PATH}**" >> $GITHUB_STEP_SUMMARY
          echo "- Merged mp3 File: **${ASSETS_PATH}/${MERGED_MP3_FILE}**" >> $GITHUB_STEP_SUMMARY
          echo "- Merged mp4 File: **${ASSETS_PATH}/${MERGED_MP4_FILE}**" >> $GITHUB_STEP_SUMMARY
          echo "- Finished mp4 File: **${ASSETS_PATH}/${MERGED_MP4_FILE}**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Workflow completed successfully 🎵" >> $GITHUB_STEP_SUMMARY
