name: Test Google Drive Access - Service Account

on:
  workflow_dispatch:

jobs:
  drive-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Write Service Account JSON
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_B64 }}" | base64 --decode > ./service-account.json

      - name: List root of shared folder
        run: |
          # Replace <YOUR_SHARED_FOLDER_ID> with the folder shared with the service account
          rclone --drive-service-account-file=./service-account.json lsd drive:1subHlJyVj0ca9ITUoyq9i89YlBgOYehV
