name: Café Asil Session Generator - Service Account

on:
  workflow_dispatch:
    inputs:
      playlist-name:
        description: 'Input to trigger the playlist workflow'
        required: true
        default: 'lofi'
        type: choice
        options:
          - lofi-moments
          - sleepy-cafe
          - study&focus-mixes
          - morning-brew

jobs:
  create-session-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare workflow variables
        run: |
          PLAYLIST_NAME="${{ github.event.inputs.playlist-name }}"
          SESSION_DATE=$(date +%Y%m%d)
          TARGET_PATH="cafe-asil:music/${PLAYLIST_NAME}/session-${SESSION_DATE}"
          ASSETS_PATH="${TARGET_PATH}/assets"
          echo "TARGET_PATH=${TARGET_PATH}" >> $GITHUB_ENV
          echo "ASSETS_PATH=${ASSETS_PATH}" >> $GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash  || { echo "Failed to install rclone"; exit 1; }
          rclone version

      - name: Write Service Account JSON
        run: |
          cat > ./service-account.json <<EOF
          ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          EOF

      - name: Create temporary rclone remote
        run: |
          rclone config create cafe-asil drive \
            service_account_file=./service-account.json \
            root_folder_id=${{ vars.GDRIVE_SHARED_FOLDER_ID }}

      - name: Create session folder (if not exists)
        run: |
          echo "Checking if session folder exists"
    
          if rclone lsd "${TARGET_PATH}" >/dev/null 2>&1; then
          echo "Session folder already exists, skipping creation."
          echo "- ${TARGET_PATH} already exists, nothing to do." >> $GITHUB_STEP_SUMMARY
          else
          echo "Session folder not found, creating..."
          rclone mkdir "${TARGET_PATH}" || { echo "Failed to create session folder"; exit 1; }
          echo "Session folder created successfully." 
          echo "- Created ${TARGET_PATH} successfully">> $GITHUB_STEP_SUMMARY
          fi

      - name: Create assets folder (if not exists)
        run: |
          echo "Checking if assets folder exists"
          if rclone lsd "${ASSETS_PATH}" >/dev/null 2>&1; then
          echo "Assets folder already exists, skipping creation."
          echo "- ${ASSETS_PATH} already exists, nothing to do." >> $GITHUB_STEP_SUMMARY
          else
          echo "Assets folder not found, creating..."
          rclone mkdir "${ASSETS_PATH}" || { echo "Failed to create assets folder"; exit 1; }
          echo "Assets folder created successfully." 
          echo "- Created ${ASSETS_PATH} successfully.">> $GITHUB_STEP_SUMMARY
          fi