name: Test Google Drive Access - Service Account

on:
  workflow_dispatch:

jobs:
  drive-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Write Service Account JSON
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" > ./service-account.json

      - name: List contents of shared folder
        run: |
          rclone lsd \
            --drive-service-account-file=./service-account.json \
            --drive-root-folder-id 1subHlJyVj0ca9ITUoyq9i89YlBgOYehV \
            drive:
