name: Test Google Drive Access - Service Account

on:
  workflow_dispatch:

jobs:
  drive-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Write Service Account JSON
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_B64 }}" | base64 --decode > ./service-account.json

      - name: Create rclone config manually
        run: |
          cat <<EOL > ./rclone.conf
[drive]
type = drive
scope = drive
service_account_file = ./service-account.json
root_folder_id = 1subHlJyVj0ca9ITUoyq9i89YlBgOYehV
EOL

      - name: List root folder in Drive
        run: |
          rclone --config ./rclone.conf lsd drive:/
