name: Test Google Drive Access - Service Account

on:
  workflow_dispatch:

jobs:
  drive-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Write Service Account JSON
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}" > ./service-account.json

      - name: Create rclone remote with service account
        run: |
          rclone config create drive drive \
            service_account_file=./service-account.json

      - name: List root folder in Drive
        run: |
          rclone lsd drive:/
