name: Test Google Drive Access - Service Account

on:
  workflow_dispatch:
    inputs:
      genre-input:
        description: 'Input to trigger the genre workflow'
        required: true
        default: 'lofi'

jobs:
  drive-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Write Service Account JSON
        run: |
          cat > ./service-account.json <<EOF
          ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          EOF

      - name: Create temporary rclone remote
        run: |
          rclone config create tempdrive drive \
            service_account_file=./service-account.json \
            root_folder_id=${{ vars.GDRIVE_SHARED_FOLDER_ID }}

      - name: List contents of shared folder
        run: |
          rclone lsd tempdrive:

      - name: Create a test folder inside shared folder
        run: |
          rclone mkdir tempdrive:music/${{ github.event.inputs.genre-input }}/test

      - name: List contents of shared folder
        run: |
          rclone lsd tempdrive: